name: Go

on:
  push:
    branches: [ master, upd_ci ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.16', '1.15' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install golint
        run: go get golang.org/x/lint/golint

      - name: Build and Run tests
        run: make
